blank_issues_enabled: false
contact_links:
  - name: ✏️ FAQ
    url: https://github.com/amd64fox/SpotX/discussions/111
    about: Read the frequently asked questions, maybe it will help solve your problem right now.